---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:
  VCENTER_DATA_CENTER:
  VCENTER_DISK_TYPE:
  EPHEMERAL_STORAGE_NAMES:
  PERSISTENT_STORAGE_NAMES:
  ICMP_CHECKS_ENABLED:
  INFRA_NETWORK_NAME:
  INFRA_VCENTER_NETWORK:
  INFRA_NW_CIDR:
  INFRA_EXCLUDED_RANGE:
  INFRA_NW_DNS:
  INFRA_NW_GATEWAY:
  INFRA_NW_AZS:
  AZ_1:
  AZ_1_CUSTER_NAME:
  AZ_1_RP_NAME:
  NTP_SERVERS:
  OPS_DIR_HOSTNAME:
  ENABLE_VM_RESURRECTOR:
  MAX_THREADS:
  TRUSTED_CERTIFICATES:
  GENERATE_VM_PASSWORDS:

inputs:
  - name: concourse-vsphere
  - name: om-cli

run:
  path: concourse-vsphere/tasks/config-opsdir/task.sh
