resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:

- name: om-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: {{github_token}} ## Optional: Removing this will cause you to hit the rate limit

- name: pivnet-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: pivnet-cli
    access_token: {{github_token}} ## Optional: Removing this will cause you to hit the rate limit

- name: concourse-vsphere
  type: git
  source:
    uri: https://github.com/c0-ops/concourse-vsphere
    branch: master

- name: pivnet-er-product
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: elastic-runtime

- name: customer-repo
  type: git
  source:
    uri: https://github.com/c0-ops/sample-customer-repo
    branch: master

jobs:

- name: upgrade-elastic-runtime-tile
  plan:
  - aggregate:
    - get: concourse-vsphere
    - get: pivnet-product
      resource: pivnet-er-product
      params:
        globs:
        - "*.pivotal"
      trigger: true
    - get: om-cli
      version: { tag: '0.18.0' }
      globs: om-linux
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"

  - task: upload-er-tile
    file: concourse-vsphere/tasks/upload-product/task.yml
    params:
      OPS_MGR_HOST: {{om_fqdn}}
      OPS_MGR_USR: {{om_usr}}
      OPS_MGR_PWD: {{om_pwd}}
      PIVNET_API_TOKEN: {{pivnet_token}}

- name: pre-install-step
  plan:
  - aggregate:
    - get: customer-repo
      trigger: true
    - get: om-cli
      globs: om-linux
      passed: [upgrade-elastic-runtime-tile]

  - task: pre-step
    file: customer-repo/tasks/pre-step/task.yml
    params:
      OPS_MGR_HOST: {{om_fqdn}}
      OPS_MGR_USR: {{om_usr}}
      OPS_MGR_PWD: {{om_pwd}}

- name: product-apply-changes
  plan:
  - aggregate:
    - get: concourse-vsphere
      trigger: true
      passed: [upgrade-elastic-runtime-tile]
    - get: om-cli
      globs: om-linux
      passed: [pre-install-step]

  - task: apply-changes
    file: concourse-vsphere/tasks/apply-changes/task.yml
    params:
      OPS_MGR_HOST: {{om_fqdn}}
      OPS_MGR_USR: {{om_usr}}
      OPS_MGR_PWD: {{om_pwd}}
